//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipwreck.Subprocessing.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shipwreck.Subprocessing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; must be an interface type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arg0MustBeAnInterfaceType {
            get {
                return ResourceManager.GetString("Arg0MustBeAnInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; must be a property expression with &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arg0MustBeAPropertyExpressionWithArg1 {
            get {
                return ResourceManager.GetString("Arg0MustBeAPropertyExpressionWithArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created temporary directory &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreatedTempDirArg0 {
            get {
                return ResourceManager.GetString("CreatedTempDirArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted temporary directory &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletedTempDirArg0 {
            get {
                return ResourceManager.GetString("DeletedTempDirArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to attach debugger &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToAttachDebuggerArg0 {
            get {
                return ResourceManager.GetString("FailedToAttachDebuggerArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to attach debugger &apos;{0}&apos;. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToAttachDebuggerArg0WithArg1 {
            get {
                return ResourceManager.GetString("FailedToAttachDebuggerArg0WithArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create a temporary directory &apos;{0}&apos;. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToCreateTempDirArg0WithArg1 {
            get {
                return ResourceManager.GetString("FailedToCreateTempDirArg0WithArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete an existing temporary directory &apos;{0}&apos;. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToDeleteExistingTempDirArg0WithArg1 {
            get {
                return ResourceManager.GetString("FailedToDeleteExistingTempDirArg0WithArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to initialize a WCF service host. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToInitializeWcfServiceHost {
            get {
                return ResourceManager.GetString("FailedToInitializeWcfServiceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening duplex service at &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeningDuplexServiceAtArg0 {
            get {
                return ResourceManager.GetString("OpeningDuplexServiceAtArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolving assembly &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResolvingAssemblyArg0 {
            get {
                return ResourceManager.GetString("ResolvingAssemblyArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Succeeded in attaching debugger &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SucceededInAttachingDebuggerArg0 {
            get {
                return ResourceManager.GetString("SucceededInAttachingDebuggerArg0", resourceCulture);
            }
        }
    }
}
